### ISSUE TITLE
$ref Resolver for OpenAPI documents

### ISSUE THREAD

**Issue by jansche** [postman-open-technologies/gsoc-2023#10]
**Summary:** Provide a robust solution for following all $ref and assembling as a single document for use at run or build time. Addressing different relative and remote paths, allowing OpenAPI definitions to be managed in an atomic way, but then assembled for use in publishing documentation, generating mock services, testing, and other lifecycle needs.
Supporting narratives:
[The Reference Rabbit Hole](https://www.asyncapi.com/blog/the-reference-rabbit-hole)
[JSON Schema bundling finally formalised](https://json-schema.org/blog/posts/bundling-json-schema-compound-documents)

Multi-spec considerations:
[Relative References in OAS](https://spec.openapis.org/oas/latest.html#relative-references-in-uris)
[$ref in JSON Schema](https://json-schema.org/understanding-json-schema/structuring.html#ref)
[$ref in AsyncAPI](https://www.asyncapi.com/docs/reference/specification/v2.2.0#referenceObject)

This is an ubiquitous challenge in working with OpenAPI, AsyncAPI, and JSON Schema.

**Skills:** Need basic understanding of OpenAPI, and JSON Schema.

**Mentors:** 2-3 mentors will be sourced from our 18+ mentors from across Postman.

**Project Size:** 175h

**Rating:** Easy to Medium

**Comment by jansche** [comment]
I think I saw a "recent" discussion on the topic. Is this still a valid project and can it be a child project to the OpenAPI Initiative?

> open source projects wishing to apply need to have a solid community; the goal of GSoC is to bring new contributors into established and welcoming communities. While you don’t have to have 50+ community members, the project also can’t have as few as three people.

@kinlane @Relequestual

**Comment by kinlane** [comment]
Some supporting narratives:

- [The Reference Rabbit Hole](https://www.asyncapi.com/blog/the-reference-rabbit-hole)
- [JSON Schema bundling finally formalised](https://json-schema.org/blog/posts/bundling-json-schema-compound-documents)

Multi-spec considerations:

- [Relative References in OAS](https://spec.openapis.org/oas/latest.html#relative-references-in-uris)
- [$ref in JSON Schema](https://json-schema.org/understanding-json-schema/structuring.html#ref)
- [$ref in AsyncAPI](https://www.asyncapi.com/docs/reference/specification/v2.2.0#referenceObject)

This is a pretty simple, yet also ubiquitous challenge in working with OpenAPI, AsyncAPI, and JSON Schema.

**Comment by Devaansh-Kumar** [comment]
Can someone please elaborate more on issue and what all topics should one go through to prepare for the same?
Some resources would also be helpful. @jansche

**Comment by Relequestual** [comment]
A bundler exists: https://github.com/hyperjump-io/json-schema-bundle (@jdesrosiers).
iirc it doesn't support OpenAPI documents of any kind.

Most downstream libraries want to remove the use of references. The formally defined bundling process DOES NOT do that, but it DOES make sure you have all the "Schema Resources" within a single document.

Why do downstream libraries want to remove references? Because understanding how to resolve them is "hard", or rather seemingly complex to understand.

The bundled format helps, but ultimatly implementations will still need to update to support it.

**Comment by MikeRalphson** [comment]
> This is a pretty simple, yet also ubiquitous challenge in working with OpenAPI, AsyncAPI, and JSON Schema.

I would take issue with the use of "pretty simple". So many existing tools get it wrong, even for OpenAPI 2.0/3.0 and their subset of JSON Schema draft-04. I also have a bundler which supports OAS 3.0, 3.1 and parts of JSON Schema 2019-09 and 2020-02, but while it still has failing test-cases for the missing `$id`/`$anchor` handling I have not released it.

**Comment by Julian** [comment]
Offtopic: @MikeRalphson not sure if I've mentioned it in a place you had your eye on, but I wrote https://github.com/python-jsonschema/referencing-suite recently as a test suite for referencing tooling. It *doesn't* yet cover the OpenAPI specs (though I intend it to), but it does cover JSON Schema ones in some ways better than the upstream general JSON Schema test suite (something I'll address soonish by copying tests upstream). But yeah if it's related to what you've got figured I'd share, and especially so if you care to share anything you have privately and/or collaborate on expanding that suite for OpenAPI.

**Comment by MikeRalphson** [comment]
Thank you @Julian that sounds very interesting for this (and my own) projects.

**Comment by jdesrosiers** [comment]
> A bundler exists: https://github.com/hyperjump-io/json-schema-bundle (@jdesrosiers).

I recently rolled this functionality into `@hyperjump/json-schema`. If anyone is looking at this as a reference, please use the new version, https://github.com/hyperjump-io/json-schema#bundling.

> iirc it doesn't support OpenAPI documents of any kind.

That's correct. It can bundle schemas using the OpenAPI 3.1 JSON Schema dialect, but doesn't understand an OpenAPI document. Adding support for understanding OpenAPI documents wouldn't be too much work, but there's not much point because there are [edge cases](https://github.com/OAI/OpenAPI-Specification/issues/2685) in OpenAPI 3.1 that the JSON Schema bundling strategy doesn't solve. It wouldn't work at all for OpenAPI 3.0 because it doesn't support the `id` keyword.

**Comment by HeeManSu** [comment]
Hey, I wanted to work on this. May I know who my mentor in this project ?

**Comment by jansche** [comment]
We're removing this project from our list of GSoC ideas after talking to contributors from OpenAPI and JSON Schema. The scope in which we could address this issue during Google Summer of Code would most probably not lead to a satisfying outcome.
