### ISSUE TITLE
AsyncAPI: Add `help/{command}` endpoint

### ISSUE THREAD

**Issue by AceTheCreator** [postman-open-technologies/gsoc-2023#21]
Suggested by Marc DiPasquale in Slack comment https://asyncapi.slack.com/archives/CQVJXFNQL/p1662141074739369?thread_ts=1661395911.924239&cid=CQVJXFNQL

We should create such an endpoint `help/{command}` to return instruction of given command to the user. For example `help/generate` should return available parameters such an available templates etc.

`help/{command}` is just a suggestion, we can go with other endpoint(s).

Also, what is very important, that endpoint should be done in a similar way as in our main CLI - https://github.com/asyncapi/cli#usage, so main help endpoint should return all available endpoints and particular one like `help/generate` should return details about given command.

Learn more here https://github.com/asyncapi/server-api/issues/144

**Mentors**: 
@BOLT04

**Project Repo:** 
https://github.com/asyncapi/server-api

**Expected Difficulty**:
Easy-Medium

**Expected Time Commitment**:
175 Hour

**Comment by sharatkatwa** [comment]
I want to work on this project,
Help me getting started

**Comment by Harsimar2000** [comment]
Greetings! My name is Harsimar, and I am thrilled about this project. I am confident that it will enable developers to build faster and better comprehend end points. To maximize my productivity, I suggest we follow agile methodologies, which have proven effective in my prior experience.

While I will have a part-time job this summer, this project will be my primary focus since it's my first GSoC, and I am genuinely enthusiastic about it. To stay organized in software development, I use Trello, which allows me to view all pending tasks in one place and sort them as I see fit. I'm well-versed in Kanban boards, having used them in previous co-op jobs.

Regarding the weekly schedule, I would appreciate learning more about the project's specifics to get a better idea of what I need to build. Thank you for offering me such a remarkable opportunity, and I wish you a pleasant day/evening.

[]https://www.linkedin.com/in/harsimar-rattan-2a45681a0/

**Comment by sv-shivansh** [comment]
Hi,
I would really appreciate it if I could get the opportunity to work on this exciting project.
I am sure that it'll be a mutually rewarding experience working together on this project as I will gain a deeper knowledge of the work and together we'll get the project done.
Hoping for a positive response.

**Comment by ctnkaan** [comment]
Hey there. I'm a final year student with 1.5 years of professional work experience using TypeScript, Node.js, React and other fun tools! I've also been maintaining an open source Cybersecurity Discord bot called Postman Sentinel that I developed for Postman for over a year. I also have 3 years of non professional community building and leading experience. I would love to write a document on my plan to contribute to this project. Is there a template I can follow for the document? @BOLT04

**Comment by BOLT04** [comment]
Hello @sharatkatwa @Harsimar2000, @sv-shivansh and @ctnkaan , thank you all for wanting to work on this project 😃 !

You can start by taking a look at the [contributing guidelines here](https://github.com/postman-open-technologies/gsoc-2023/blob/main/CONTRIBUTOR_GUIDANCE.md) and follow the checklist 👍 

As part of GSoC, you have to submit a proposal first and we'll review it. But you can also start engaging with the AsyncAPI community on any project you want. You can learn more details [here](https://summerofcode.withgoogle.com/how-it-works) too.
For the proposals, you can contact me by email: [davidpereira2938@gmail.com](mailto:davidpereira2938@gmail.com)

Looking forward to hearing from you all 🙂

**Comment by ctnkaan** [comment]
Alright, thanks! I'll reach out to you after completing the proposal. 😄

**Comment by BOLT04** [comment]
Great to hear that @ctnkaan 👍, just a reminder about when the applications start, you can see the [details here](https://opensource.googleblog.com/2023/02/mentor-organizations-announced-for.html):
> The 2023 GSoC program is open to students and to beginners in open source software development. Contributor applications will open on Monday, March 20, 2023 at 18:00 UTC with a deadline of Tuesday, April 4, 2023 18:00 UTC to submit your application (including your project proposal

**Comment by prayutsu** [comment]
@BOLT04 I can't find any starter issues in the [repository](https://github.com/asyncapi/server-api/issues) of this project. Can you please suggest some?

**Comment by shubhsinha** [comment]
I am confident that I possess the requisite skills to contribute to this project. I have practical experience in developing RESTful APIs and working with command-line interface (CLI) tools. Furthermore, I am well-versed with the AsyncAPI CLI tool and its documentation structure, which makes me a suitable candidate for this project.

**Comment by princerajpoot20** [comment]
Hello,
I’m Prince Rajpoot, 2nd year B-tech student.
I want to contribute to Postman as a part of GSOC 2023.

Postman is a popular tool for API development and testing, and contributing to the project can help you learn more about this area.

I want to suggest an idea:

Data Generator - Random data generator like email, names, zip/postal codes, addresses, mobile number and provide the facility to verify response in random data generator.

What are your views on this? Can I contribute to this idea as a part of GSOC-2023?
I'm really passionate about this project and I believe it has the potential to make a real impact. I would be so grateful for any help you could provide.


-Prince Rajpoot
[prince.rajpoot.20@gmail.com](mailto:prince.rajpoot.20@gmail.com)

**Comment by VishrutAggarwal** [comment]
Hello there! 

I was going through project ideas for GSoC and I am very interested in the project you have proposed. Creating an endpoint like help/{command} to provide instructions for a given command is a great idea, and I agree with the suggestion. I fully understand that it's important to make sure the endpoint is consistent with the main CLI and provides all the necessary information for users. I will definitely take a look at the asyncapi/cli#usage to make sure that I am in accordance with the guidelines. 

The expected difficulty and time commitment also seem reasonable to me. I am also interested in tackling smaller issues that can help me get more familiar with the codebase and show my abilities. Are there any first-time contributor issues available that I could work on to get started? 

Looking forward to becoming a potential candidate and contribute to this project!

**Comment by Akshat171** [comment]
Hello mentor @BOLT04 ,

My name is Akshat jangid, and I am excited to introduce myself to this community. I am a MERN stack developer with 2.5 years of experience. My skills include ReactJS, NodeJS, nextjs , TypeScript, RestfulAPI Express and databases like MongoDB.

I am very interested in contributing to your organization and would love to be a part of it. I am passionate about programming and enjoy working on projects that challenge me to learn new skills and technologies.

**Comment by snehalchaudhari98** [comment]
Hi everyone, I am Snehal Chaudhari.  I am a Computer Science graduate student and I have used Postman for more that 3 years within my employment. Previously I have worked on collaboration and collection services that's which had a feature on similar lines.  I feel like this is a really interesting task and would like to contribute on the same. After reviewing the contributors guideline I believe my past experience of 3 years would be helpful. I have experience in working with RESTful service and SOAP services, Java, Node.js, React.js, TypeScript, etc. After using Postman as a student till working professional, I feel this would be a good way to contribute back to the same community. I would be interested in joining any discussion session or forums for this task (if there are any.)

**Comment by prayutsu** [comment]
Hi all, I am Abhay Garg, a final year Computer Science undergraduate at IIIT Lucknow, India. I am an open-source enthusiast and have also been a Google Summer of Code student in 2021 with Oppia. You can find more details [here](https://summerofcode.withgoogle.com/archive/2021/projects/5415259354955776). I also did an internship with Walmart in the summer of 2022 and I am looking forward to having a great learning experience this summer as well.

> What interests you most about this project?

The project idea is simple yet useful. It would enable users to quickly update the URL and see the docs related to different tools. I haven't made many open-source contributions in node.js repos so it would be a new learning experience for me.

> As mentors and project coordinators, how can we get the best out of you?

From my previous GSoC experience, I learned communication is the key. Also, I believe before actual coding, it is really important to properly document feature requirements and an outline of the implementation in the proposal. Before proposal submission, I'll try to get as many reviews as possible.

> Is there anything that you’ll be studying or working on whilst working alongside us?

Yes, I am also working as an intern at CRED, but the workload is very less and this is one of the reasons that I want to spend my summer completing a GSoC project that adds new skills to my resume. On top of that, I am a nerd when it comes to programming and I can code all day without getting tired ;)
Also our university curriculum only includes one project for the final semester (and not any subjects) and if possible (and also if get selected) I'll try to present this GSoC project as my final sem project.

> We'd love to hear a bit on your work preferences, e.g. how you keep yourself organized, what tools you use, etc?

To keep myself organized, I use Notion to make my notes and keep track of my tasks. To learn any new technologies, I generally go through the documentation of that technology and make a small project on it.

> Once you’ve selected a project from the [ideas](https://github.com/postman-open-technologies/gsoc-2023/issues?q=is%3Aissue+is%3Aopen+label%3Afinal+label%3Aideas) section, please suggest a weekly schedule with clear milestones and deliverables around it. Alternatively, if you want to propose your own idea then please include outline, goals, and a well-defined weekly schedule with clear milestones and deliverables.

To answer this section, I need to gathere more details around feature requirements. I will update the timelines here and also in the proposal once I am clear about the project expectations.

**Comment by prayutsu** [comment]
@BOLT04 I have a few doubts -
1. I am assuming that we only want to create these endpoints for CLI commands or are there any other tools also for which we need to add these endpoints?
2. I am able to recognize these 14 endpoints that should be added for CLI commands, please let me know if I am missing any?
```
/help
     /config
             /context
     /generate
             /fromTemplate
             /models
     /start
             /studio
     /convert
     /diff
     /new
     /optimize
     /start
     /validate         
```

**Comment by BOLT04** [comment]
> @BOLT04 I have a few doubts -
> 
>     1. I am assuming that we only want to create these endpoints for CLI commands or are there any other tools also for which we need to add these endpoints?
> 
>     2. I am able to recognize these 14 endpoints that should be added for CLI commands, please let me know if I am missing any?
> 
> 
> ```
> /help
>      /config
>              /context
>      /generate
>              /fromTemplate
>              /models
>      /start
>              /studio
>      /convert
>      /diff
>      /new
>      /optimize
>      /start
>      /validate         
> ```


hi @prayutsu 🙂, for your first question we could focus mainly on the CLI commands, but take into consideration the extensibility of the implementation.

Regarding your 2nd question, we would only have 1 API endpoint probably, since the API resource we want to expose is "help". The list you provided is basically the options you have for the path parameter `command`. Since we only have one path parameter, the challenge would be to either design the API in a way where you can have that hierarchy of URIs, or provide the command (and sub-commands in case of `generate` for example) in the query string or request body.
Feel free to suggest ideas for the API design 👍

**Comment by prayutsu** [comment]
@BOLT04 Thanks for providing clarification on the above questions. 

I wanted to clarify one more thing - would the APIs developed through this project be used [here](https://www.asyncapi.com/docs)? If yes, then would these APIs be a part of docs or do we want to keep them separate?

**Comment by BOLT04** [comment]
hi @sharatkatwa @Harsimar2000 @sv-shivansh @ctnkaan @snehalchaudhari98 @Akshat171 @VishrutAggarwal @princerajpoot20 @shubhsinha , just a quick reminder if you're interested in this project you need to submit your proposal on the google summer of code website until April 4th 👍 
We'll review the proposals sent there.

**Comment by BOLT04** [comment]
> @BOLT04 Thanks for providing clarification on the above questions.
> 
> I wanted to clarify one more thing - would the APIs developed through this project be used [here](https://www.asyncapi.com/docs)? If yes, then would these APIs be a part of docs or do we want to keep them separate?

@prayutsu they probably won't be in those docs, at least not for now.

**Comment by Gbahdeyboh** [comment]
Hey folks, the Postman OSPO is live for a Google Summer of Code Q&A session. #gsoc
Link to zoom session: [go.pstmn.io/gsoc-qa](http://go.pstmn.io/gsoc-qa)

**Comment by Dev-29** [comment]
Hi @BOLT04 I am Dev, a 3rd year computer science student at VIT University, Vellore and I would love to work on this project. I have around an year of experience working with NodeJS, MongoDB, Express, and creating RESTful APIs. I am highly looking forward to be a potential contributor for this project and organization!

**Comment by po1so9** [comment]
Hello everyone, I am Furqan Ahmad Khan, a 3rd-year Computer Science student. This is my first time contributing to an open-source project. I also did an internship with Sociohub Media in the winter of 2022 and I am looking forward to having a great learning experience this summer.

#### What interests you most about this project?

I want to learn more about API building, I recently started developing APIs using node.js, Express.js, and MongoDB.
The project idea felt like a good fit for me and the endpoint would be very useful that would enable users to learn about the tools available very easily and quickly.

#### As mentors and project coordinators, how can we get the best out of you?

From my previous internship experience, I learned communication is the key. As a mentor, you can tell me what to learn and can help me a little if I get stuck and I'll do my best.

#### Is there anything that you’ll be studying or working on whilst working alongside us?

Yes, I am currently preparing for my finals, but I can manage to work on this project and this is one of the reasons that I want to spend my summer completing a GSoC project that adds new skills to my resume. Also, when it comes to learning, I can code all day without distraction or taking long breaks.

#### We'd love to hear a bit on your work preferences, e.g. how you keep yourself organized, what tools you use, etc?

To keep myself organized, I simply use a notebook and a pen to keep track of my tasks. To learn any new technologies, I generally go through the documentation and some video tutorials of that technology and make a small project on it.

#### Once you’ve selected a project from the [ideas](https://github.com/postman-open-technologies/gsoc-2023/issues?q=is%3Aissue+is%3Aopen+label%3Afinal+label%3Aideas) section, please suggest a weekly schedule with clear milestones and deliverables around it. Alternatively, if you want to propose your own idea then please include outline, goals, and a well-defined weekly schedule with clear milestones and deliverables.

I cannot answer this question precisely right now because this is my first time contributing to such a project but as we go along I can tell the exact time by going through the requirements and my learning speed.

**Comment by princerajpoot20** [comment]
Hey, I hope this message finds you well. I am writing to inquire about the proposal I submitted for the GSoC program. I would greatly appreciate any feedback you have on it and if there are any changes you would like me to make.

Thank you for considering my proposal, and I look forward to hearing back from you.

Best regards,
-Prince Rajpoot

**Comment by AishwaryJain07** [comment]
hey @BOLT04 
Greetings to you.
I wanted to share my proposal for GSOC'24 , can you please tell where to send .
I'm Aishwary Jain-from India
Computer science Undergraduate
skillset: Django, Golang, Python, C, C++, Javascript, HTML, CSS, MySql..
would be happy to work with you and learn new things.

**Comment by benjagm** [comment]
Closed as completed as part of 2023 edition.
